### ISSUE TITLE
Some questions about your proposed Rotated RoI

### ISSUE THREAD

**Issue by mjq11302010044** [weijiawu/TransDETR#13]
![image](https://user-images.githubusercontent.com/6492801/178891993-7b21393b-da36-4b21-b112-d828c021977b.png)
Could you please verify the difference of your Rotated RoI and the Rotated RoI Pooling and Alignment operations proposed in [1],[2] and [3]? Though your proposed Rotated RoI is different from RoIRotate, (you mentioned you use bilinear interpolation to map the feature grid) It is the same component that has been proposed in [1-3].  If there is no difference between the two, please cite these papers in your paper and remove the "propose" claim.

[1] Ma, J., Shao, W., Ye, H., Wang, L., Wang, H., Zheng, Y., & Xue, X. (2018). Arbitrary-oriented scene text detection via rotation proposals. IEEE Transactions on Multimedia, 20(11), 3111-3122.
[2] He, T., Tian, Z., Huang, W., Shen, C., Qiao, Y., & Sun, C. (2018). An end-to-end textspotter with explicit alignment and attention. In Proceedings of the IEEE conference on computer vision and pattern recognition (pp. 5020-5029).
[3] Ma, J. (2020). Rrpn++: Guidance towards more accurate scene text detection. arXiv preprint arXiv:2009.13118.

**Comment by weijiawu** [comment]
> 



> ![image](https://user-images.githubusercontent.com/6492801/178891993-7b21393b-da36-4b21-b112-d828c021977b.png) Could you please verify the difference of your Rotated RoI and the Rotated RoI Pooling and Alignment operations proposed in [1],[2] and [3]? Though your proposed Rotated RoI is different from RoIRotate, (you mentioned you use bilinear interpolation to map the feature grid) It is the same component that has been proposed in [1-3]. If there is no difference between the two, please cite these papers in your paper and remove the "propose" claim.
> 
> [1] Ma, J., Shao, W., Ye, H., Wang, L., Wang, H., Zheng, Y., & Xue, X. (2018). Arbitrary-oriented scene text detection via rotation proposals. IEEE Transactions on Multimedia, 20(11), 3111-3122. [2] He, T., Tian, Z., Huang, W., Shen, C., Qiao, Y., & Sun, C. (2018). An end-to-end textspotter with explicit alignment and attention. In Proceedings of the IEEE conference on computer vision and pattern recognition (pp. 5020-5029). [3] Ma, J. (2020). Rrpn++: Guidance towards more accurate scene text detection. arXiv preprint arXiv:2009.13118.

Thank you for your suggestion.  I will cite these papers and present further discussion. 
1.  RRPN[1] uses max pooling to map the feature, which is different from ours. 
2.  [2] is not an affine transformation-based method.
3.  RRPN++[3] is the extended version of RRPN, and adopts bilinear interpolation to replace the max pooling.

Therefore, our Rotated RoI seems to be similar to the RRPN++. We will remove the "propose" claim and modify to the claim "To enable end-to-end training, similar to RRPN~\cite{ma2018arbitrary}, RRPN++~\cite{ma2020rrpn++}, we adopt the Rotated Region-of-Interest~(Rotated RoI) to extract the features of each text from the output feature map of upsampling. "



> ![image](https://user-images.githubusercontent.com/6492801/178891993-7b21393b-da36-4b21-b112-d828c021977b.png) Could you please verify the difference of your Rotated RoI and the Rotated RoI Pooling and Alignment operations proposed in [1],[2] and [3]? Though your proposed Rotated RoI is different from RoIRotate, (you mentioned you use bilinear interpolation to map the feature grid) It is the same component that has been proposed in [1-3]. If there is no difference between the two, please cite these papers in your paper and remove the "propose" claim.
> 
> [1] Ma, J., Shao, W., Ye, H., Wang, L., Wang, H., Zheng, Y., & Xue, X. (2018). Arbitrary-oriented scene text detection via rotation proposals. IEEE Transactions on Multimedia, 20(11), 3111-3122. [2] He, T., Tian, Z., Huang, W., Shen, C., Qiao, Y., & Sun, C. (2018). An end-to-end textspotter with explicit alignment and attention. In Proceedings of the IEEE conference on computer vision and pattern recognition (pp. 5020-5029). [3] Ma, J. (2020). Rrpn++: Guidance towards more accurate scene text detection. arXiv preprint arXiv:2009.13118.

Thank you for your suggestion.  I will cite these papers and present further discussion. 
1.  RRPN[1] uses max pooling to map the feature, which is different from ours. 
2.  [2] is not an affine transformation-based method.
3.  RRPN++[3] is the extended version of RRPN, and adopts bilinear interpolation to replace the max pooling.

Therefore, our Rotated RoI seems to be similar to the RRPN++. We will remove the "propose" claim and modify to the claim "To enable end-to-end training, similar to RRPN~\cite{ma2018arbitrary}, RRPN++~\cite{ma2020rrpn++}, we adopt the Rotated Region-of-Interest~(Rotated RoI) to extract the features of each text from the output feature map of upsampling. "

**Comment by weijiawu** [comment]
> ![image](https://user-images.githubusercontent.com/6492801/178891993-7b21393b-da36-4b21-b112-d828c021977b.png) Could you please verify the difference of your Rotated RoI and the Rotated RoI Pooling and Alignment operations proposed in [1],[2] and [3]? Though your proposed Rotated RoI is different from RoIRotate, (you mentioned you use bilinear interpolation to map the feature grid) It is the same component that has been proposed in [1-3]. If there is no difference between the two, please cite these papers in your paper and remove the "propose" claim.
> 
> [1] Ma, J., Shao, W., Ye, H., Wang, L., Wang, H., Zheng, Y., & Xue, X. (2018). Arbitrary-oriented scene text detection via rotation proposals. IEEE Transactions on Multimedia, 20(11), 3111-3122. [2] He, T., Tian, Z., Huang, W., Shen, C., Qiao, Y., & Sun, C. (2018). An end-to-end textspotter with explicit alignment and attention. In Proceedings of the IEEE conference on computer vision and pattern recognition (pp. 5020-5029). [3] Ma, J. (2020). Rrpn++: Guidance towards more accurate scene text detection. arXiv preprint arXiv:2009.13118.

Thank you for your suggestion.  I will cite these papers and present further discussion. 
1.  RRPN[1] uses max pooling to map the feature, which is different from ours. 
2.  [2] is not an affine transformation-based method.
3.  RRPN++[3] is the extended version of RRPN, and adopts bilinear interpolation to replace the max pooling.

Therefore, our Rotated RoI seems to be similar to the RRPN++. We will remove the "propose" claim and modify to the claim "To enable end-to-end training, similar to RRPN, RRPN++, we adopt the Rotated Region-of-Interest~(Rotated RoI) to extract the features of each text from the output feature map of upsampling. "

**Comment by mjq11302010044** [comment]
@weijiawu Thanks for solving my doubts about the papers. Overall,  it is still a good work for ECCV2022. Congrats.
