### ISSUE TITLE
关于测试问题

### ISSUE THREAD

**Issue by josephzpng** [weijiawu/TransDETR#20]
您好 很感谢您开源这么好的工作！
我尝试用开源的模型对ICDAR2015进行测试，得到结果后提交到了 https://rrc.cvc.uab.es/?ch=3&com=introduction，但是验证结果一直为 0，想请问可能是什么原因呢？

**Comment by IncludeMathH** [comment]
请问您是如何解决这个问题的？另外在加载模型时我看到了部分参数维度不匹配的警告信息，请问是因为这个么？还是说只要等一会网站上就能输出结果呀？

**Comment by weijiawu** [comment]
可以先可视化gt在video上看看效果，如果正确，可能就是ICDAR2015官方格式没有对齐。            官网网站评估需要时间，一般5分钟-30分钟不等
