### ISSUE TITLE
请问，为什么./models/Rotated_ROIAlign是空的？

### ISSUE THREAD

**Issue by Sisi0518** [weijiawu/TransDETR#4]
请问，为什么./models/Rotated_ROIAlign是空的？没有办法安装

**Comment by weijiawu** [comment]
Thanks for the attention. The complete code for Rotated_ROIAlign has been released in [./models/Rotated_ROIAlign](https://github.com/weijiawu/TransDETR/tree/main/models/Rotated_ROIAlign)
