### ISSUE TITLE
Error in the evaluation script 

### ISSUE THREAD

**Issue by maherr13** [weijiawu/TransDETR#6]
Hello, excellent work!

I was trying the evaluation script then I got this error that I couldn't pass.

![image](https://user-images.githubusercontent.com/83926003/169906234-24763e86-6f61-4a6a-a20a-24ed8ee63b34.png)

what could be the issue here ??

**Comment by weijiawu** [comment]
you need build the MultiScaleDeformableAttention:
cd ./models/ops
sh ./make.sh
