### ISSUE TITLE
import error 

### ISSUE THREAD

**Issue by Epiphqny** [weijiawu/TransDETR#8]
The Rotated_ROIAlign module has already been built, but the error raises when training:
`import rotated_roi as _C
ModuleNotFoundError: No module named 'rotated_roi'`

**Comment by weijiawu** [comment]
I guess that the error is from the python import path error.

Maybe you can add the rotated_roi path to the python default path by
`export PYTHONPATH=$PYTHONPATH: ./rroi_align/build/lib.linux-x86_64-3.7`

**Comment by Epiphqny** [comment]
> export PYTHONPATH=$PYTHONPATH

Thanks, it works.

**Comment by Epiphqny** [comment]
@weijiawu There are still some problems, could I have your wechat? thanks!

**Comment by weijiawu** [comment]
15167756092

**Comment by maherr13** [comment]
I hope you share the problems-fix

**Comment by yywwwwww** [comment]
> ![Screenshot from 2022-06-02 14-36-28](https://user-images.githubusercontent.com/102550268/171601877-009834d9-e9a7-49c8-97a3-3356d3c83d59.png)

I have the same problem. How did you solve it？Thanks

**Comment by weijiawu** [comment]
> 

https://github.com/open-mmlab/mmsegmentation/issues/943 may help you.

And the version of mmcv for me is 1.7.1
<img width="387" alt="image" src="https://user-images.githubusercontent.com/40711216/215397078-4bca3562-ba76-4d0c-8385-9c1900c94047.png">
